# Generated by Django 4.0.3 on 2022-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('emp_id', models.AutoField(db_column='emp_id', primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(db_column='employee_first_name', default='', max_length=255)),
                ('employee_last_name', models.CharField(db_column='employee_last_name', default='', max_length=255)),
                ('employee_surname', models.CharField(db_column='employee_surname', default='', max_length=255)),
                ('employee_salary', models.CharField(db_column='employee_salary', max_length=255)),
                ('dob', models.CharField(db_column='dob', max_length=255)),
                ('gender', models.CharField(db_column='gender', max_length=255)),
            ],
            options={
                'db_table': 'employee_master',
            },
        ),
    ]
